language: java
addons:
  sonarcloud:
    organization: "egoarka-github" # the key of the org you chose at step #3
env:
  - WORK_DIR=lab1/app
script:
  - cd $WORK_DIR && mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  # - cd $WORK_DIR && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V && mvn test -B && sonar-scanner